name: "ecomm_analysis"
version: "1.0.0"
config-version: 2

profile: ecomm_analysis

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

# Global model configs
models:
  ecomm_analysis:
    # Staging: views for lightweight transformation
    staging:
      +materialized: view
      +schema: staging

    # Intermediate: ephemeral or views for complex joins
    intermediate:
      +materialized: ephemeral

    # Marts: tables for BI consumption
    marts:
      +materialized: table
      core:
        +schema: core
      analytics:
        +schema: analytics

tests:
  +store_failures: true
  +severity: warn

vars:
  # Date range filter for incremental loads
  start_date: "2016-01-01"
  end_date: "2018-12-31"
