ecomm_analysis:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '/tmp/dev.duckdb') }}"
      schema: main
      threads: 4
    prod:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '/tmp/prod.duckdb') }}"
      schema: prod
      threads: 8
