ecomm_analysis:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/rohitha/github-projects/ecomm-analysis/dev.duckdb
      schema: main
      threads: 4
    prod:
      type: duckdb
      path: /Users/rohitha/github-projects/ecomm-analysis/prod.duckdb
      schema: prod
      threads: 8
